version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  landing:
    build:
      context: ./notanacional
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  app-notanacional:
    build:
      context: ./app-notanacional
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=mysql://notanacional_user:secure_user_password_homolog@host.docker.internal:3306/notanacional_homolog
    ports:
      - "3001:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  notanacional-hub:
    build:
      context: ./notanacional-hub
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=mysql://notanacional_user:secure_user_password_homolog@host.docker.internal:3306/notanacional_homolog
    ports:
      - "3002:3000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  notanacional-hub-api:
    build:
      context: ./notanacional-hub-api
      dockerfile: ./Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=notanacional_homolog;User=notanacional_user;Password=secure_user_password_homolog;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./notanacional-hub-api/uploads:/app/uploads
    restart: unless-stopped

volumes:
  mysql_data:
